workflows:
  nomzbank-build:
    name: Build Android and iOS
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build iOS App (no code-signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - nuurosman77@gmail.com
